# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_time <- function(times) {
    .Call('_CTMISD_get_time', PACKAGE = 'CTMISD', times)
}

init_p0 <- function(times) {
    .Call('_CTMISD_init_p0', PACKAGE = 'CTMISD', times)
}

calc_br <- function(p0, times) {
    .Call('_CTMISD_calc_br', PACKAGE = 'CTMISD', p0, times)
}

calc_br_nonstat <- function(p0, times, z, tau) {
    .Call('_CTMISD_calc_br_nonstat', PACKAGE = 'CTMISD', p0, times, z, tau)
}

calc_d <- function(dist_mat2, np) {
    .Call('_CTMISD_calc_d', PACKAGE = 'CTMISD', dist_mat2, np)
}

get_pix <- function(x_grid, y_grid, lat, lon, x_pix, y_pix) {
    .Call('_CTMISD_get_pix', PACKAGE = 'CTMISD', x_grid, y_grid, lat, lon, x_pix, y_pix)
}

calc_tau <- function(x_pix, y_pix, p0, di, lon, lat, times) {
    .Call('_CTMISD_calc_tau', PACKAGE = 'CTMISD', x_pix, y_pix, p0, di, lon, lat, times)
}

get_h <- function(p0, dist_mat, dist_ints, n_ints) {
    .Call('_CTMISD_get_h', PACKAGE = 'CTMISD', p0, dist_mat, dist_ints, n_ints)
}

get_g <- function(p0, time_mat, time_ints, n_ints) {
    .Call('_CTMISD_get_g', PACKAGE = 'CTMISD', p0, time_mat, time_ints, n_ints)
}

update_p <- function(p0, dist_mat, br, predg, predh, predk, sp) {
    .Call('_CTMISD_update_p', PACKAGE = 'CTMISD', p0, dist_mat, br, predg, predh, predk, sp)
}

check_p <- function(p0, p) {
    .Call('_CTMISD_check_p', PACKAGE = 'CTMISD', p0, p)
}

get_theta <- function(min_int, max_int, diff_mat, p0, mark_check) {
    .Call('_CTMISD_get_theta', PACKAGE = 'CTMISD', min_int, max_int, diff_mat, p0, mark_check)
}

